import pricesJson from "./steam-prices.generated.json";
import { decodeItemKey, itemCatalogEntry, ITEM_GRADES } from "./items";

// ---------------------------------------------------------------------------
// Steam Community Market prices (THB) for TBH items.
//
// The game's items trade for real money on the Steam Community Market
// (appid 3678970). Because we already know the exact inventory from the save,
// we skip the screenshot/OCR step the reference price-calculator needs — we just
// map each item to its market_hash_name and look the price up.
//
// Snapshot generated by agent/fetch_steam_prices.py (run periodically). Prices
// move slowly enough that a cached snapshot reflects real resale value well.
// ---------------------------------------------------------------------------
export interface PriceRow {
  lowest: number | null; // cheapest current sell listing ("ราคาขาย" / ask)
  median: number | null; // median of recent sales ("อัตรากลาง")
  volume: number; // units sold in the last 24h
  buyOrder?: number | null; // highest current buy order ("ราคาซื้อ" / bid)
}

interface PriceSnapshot {
  currency: string;
  appId: number;
  fetchedAt: string;
  count: number;
  prices: Record<string, PriceRow>;
}

const SNAP = pricesJson as unknown as PriceSnapshot;

export const STEAM_APP_ID = SNAP.appId;
export const PRICE_CURRENCY = SNAP.currency; // "THB"
export const PRICES_FETCHED_AT = SNAP.fetchedAt;

/**
 * Steam Community Market hash name for an item key, or null when the item is not
 * tradable (low-grade gear) or has no English name. Mirrors the mapping in
 * agent/fetch_steam_prices.py exactly:
 *   material/special : plain English name         e.g. "Minor Ruby"
 *   equipment (g>=3) : "<en> (<Grade>) <Variant>"  e.g. "Bastard Sword (Immortal) A"
 * Equipment below Legendary (grade 3) is not listed on the market.
 */
export function marketHashName(itemKey: number): string | null {
  const cls = Math.floor(itemKey / 100000);
  const e = itemCatalogEntry(itemKey);
  if (!e?.en) return null;
  if (cls === 1 || cls === 9) return e.en; // material / special
  const { grade, variant } = decodeItemKey(itemKey);
  if (grade < 3) return null; // not tradable
  const label = ITEM_GRADES[grade]?.en;
  if (!label) return null;
  const letter = String.fromCharCode(65 + Math.max(variant - 1, 0));
  return `${e.en} (${label}) ${letter}`;
}

export interface ItemPrice {
  hashName: string;
  lowest: number | null; // lowest current sell listing (the "ask")
  median: number | null; // median of recent sales
  buyOrder: number | null; // highest current buy order (the "bid")
  volume: number;
  value: number | null; // median preferred, else lowest listing
  listed: boolean; // present in the price snapshot
}

/** Price for an item key, or null when the item isn't tradable on the market. */
export function itemPrice(itemKey: number): ItemPrice | null {
  const hashName = marketHashName(itemKey);
  if (!hashName) return null;
  const row = SNAP.prices[hashName];
  if (!row) {
    return { hashName, lowest: null, median: null, buyOrder: null, volume: 0, value: null, listed: false };
  }
  const value = row.median ?? row.lowest ?? null;
  return {
    hashName,
    lowest: row.lowest,
    median: row.median,
    buyOrder: row.buyOrder ?? null,
    volume: row.volume,
    value,
    listed: true,
  };
}

// ---------------------------------------------------------------------------
// Price metrics — which number to treat as an item's worth.
//   median : มูลค่ากลางจากยอดขายล่าสุด — the realistic resale value (default).
//   sell   : ราคาตั้งขายต่ำสุด (lowest listing) — can be wildly off for illiquid
//            items, so it's a reference, not the default.
//   buy    : ราคารับซื้อสูงสุด (highest buy order) — what you'd get selling now.
//            Only available when the snapshot was built with a logged-in Steam
//            session; absent in the anonymous snapshot, so the UI hides it then.
// ---------------------------------------------------------------------------
export type PriceMetric = "median" | "sell" | "buy";

export const PRICE_METRICS: { key: PriceMetric; th: string; hint: string }[] = [
  { key: "median", th: "ราคากลาง", hint: "มูลค่ากลางจากยอดขายล่าสุด (แนะนำ)" },
  { key: "sell", th: "ราคาตั้งขาย", hint: "ราคาตั้งขายต่ำสุดในตลาดตอนนี้" },
  { key: "buy", th: "ราคารับซื้อ", hint: "ราคารับซื้อสูงสุด — ขายได้ทันทีเท่านี้" },
];

/** The value of an item under a given metric, or null when unavailable. */
export function priceByMetric(p: ItemPrice | null, metric: PriceMetric): number | null {
  if (!p) return null;
  if (metric === "sell") return p.lowest;
  if (metric === "buy") return p.buyOrder;
  return p.median ?? p.lowest; // "median" with a sensible fallback
}

/** Whether any snapshot row carries buy-order data (drives the "buy" toggle). */
export function hasBuyOrders(): boolean {
  for (const k in SNAP.prices) {
    if (SNAP.prices[k]?.buyOrder != null) return true;
  }
  return false;
}

/** Public Steam Market listing URL for a market hash name. */
export function steamMarketUrl(hashName: string): string {
  return `https://steamcommunity.com/market/listings/${STEAM_APP_ID}/${encodeURIComponent(hashName)}`;
}

export interface PortfolioValue {
  total: number; // sum of priced item values (THB)
  pricedCount: number; // items that contributed a value
  tradableCount: number; // items that have a market hash name
  unpricedCount: number; // tradable but missing a snapshot price
}

/** Aggregate market value of a set of items (e.g. bag + stash). */
export function portfolioValue(items: { itemKey: number }[]): PortfolioValue {
  let total = 0;
  let pricedCount = 0;
  let tradableCount = 0;
  let unpricedCount = 0;
  for (const it of items) {
    const p = itemPrice(it.itemKey);
    if (!p) continue;
    tradableCount += 1;
    if (p.value != null) {
      total += p.value;
      pricedCount += 1;
    } else {
      unpricedCount += 1;
    }
  }
  return { total, pricedCount, tradableCount, unpricedCount };
}

const BAHT = new Intl.NumberFormat("th-TH", { maximumFractionDigits: 2 });
const BAHT0 = new Intl.NumberFormat("th-TH", { maximumFractionDigits: 0 });

/** "฿3,774.64" / "฿6,363" (drops decimals at >= ฿1,000). null → "—". */
export function formatBaht(n: number | null | undefined): string {
  if (n == null) return "—";
  return "฿" + (n >= 1000 ? BAHT0.format(n) : BAHT.format(n));
}

/** Compact for large totals: 14554 → "฿14.6K". */
export function formatBahtCompact(n: number | null | undefined): string {
  if (n == null) return "—";
  return (
    "฿" +
    new Intl.NumberFormat("en", { notation: "compact", maximumFractionDigits: 1 }).format(n)
  );
}
